// http://qurancoaching.com/99-names-allah-swt-al-asma-ul-husna-%D8%A7%D9%8E%D9%84%D8%A7%D8%B3%D9%92%D9%85%D9%8E%D8%A7%D8%A1%D9%8F-%D8%A7%D9%84%D9%92%D8%AD%D9%8F%D8%B3%D9%86%D8%A7%D9%89/

module.exports = [
  {
    "arabic": "الرَّحْمَنُ",
    "latin": "Ar-Rahmaan",
    "transliteration": "Yang Maha Pengasih",
    "meaning": "Allah SWT mempunyai kasih dan sayang yang sangat luas sekali, muliputi dari seluruh makhluknya Allah SWT. Allah SWT mengasihi semua makhluknya dengan memberikan berbagai dengan kenikmatan.",
  },
  {
    "arabic": "الرَّحِيمُ",
    "latin": "Ar-Raheem",
    "transliteration": "The Merciful",
    "meaning": "He who acts with extreme kindness",
  },
  {
    "arabic": "الْمَلِكُ",
    "latin": "Al-Malik",
    "transliteration": "The Eternal Lord",
    "meaning": "The Sovereign Lord, The One with the complete Dominion, the One Whose Dominion is clear from imperfection",
  },
  {
    "arabic": "الْقُدُّوسُ",
    "latin": "Al-Quddus",
    "transliteration": "The Most Sacred",
    "meaning": "The One who is pure from any imperfection and clear from children and adversaries",
  },
  {
    "arabic": "السَّلاَمُ",
    "latin": "As-Salam",
    "transliteration": "The Embodiment of Peace",
    "meaning": "The One who is free from every imperfection.",
  },
  {
    "arabic": "الْمُؤْمِنُ",
    "latin": "Al-Mu’min",
    "transliteration": "The Infuser of Faith",
    "meaning": "The One who witnessed for Himself that no one is God but Him. And He witnessed for His believers that they are truthful in their belief that no one is God but Him",
  },
  {
    "arabic": "الْمُهَيْمِنُ",
    "latin": "Al-Muhaymin",
    "transliteration": "The Preserver of Safety",
    "meaning": "The One who witnesses the saying and deeds of His creatures",
  },
  {
    "arabic": "الْعَزِيزُ",
    "latin": "Al-Aziz",
    "transliteration": "The Mighty One",
    "meaning": "The Strong, The Defeater who is not defeated",
  },
  {
    "arabic": "الْجَبَّارُ",
    "latin": "Al-Jabbar",
    "transliteration": "The Omnipotent One",
    "meaning": "The One that nothing happens in His Dominion except that which He willed",
  },
  {
    "arabic": "الْمُتَكَبِّرُ",
    "latin": "Al-Mutakabbir",
    "transliteration": "The Dominant One",
    "meaning": "The One who is clear from the attributes of the creatures and from resembling them.",
  },
  {
    "arabic": "الْخَالِقُ",
    "latin": "Al-Khaaliq",
    "transliteration": "The Creator",
    "meaning": "The One who brings everything from non-existence to existence",
  },
  {
    "arabic": "الْبَارِئُ",
    "latin": "Al-Baari",
    "transliteration": "The Evolver",
    "meaning": "The Maker, The Creator who has the Power to turn the entities.",
  },
  {
    "arabic": "الْمُصَوِّرُ",
    "latin": "Al-Musawwir",
    "transliteration": "The Flawless Shaper",
    "meaning": "The One who forms His creatures in different pictures.",
  },
  {
    "arabic": "الْغَفَّارُ",
    "latin": "Al-Ghaffaar",
    "transliteration": "The Great Forgiver",
    "meaning": "The Forgiver, The One who forgives the sins of His slaves time and time again.",
  },
  {
    "arabic": "الْقَهَّارُ",
    "latin": "Al-Qahhaar",
    "transliteration": "The All-Prevailing One",
    "meaning": "The Dominant, The One who has the perfect Power and is not unable over anything.",
  },
  {
    "arabic": "الْوَهَّابُ",
    "latin": "Al-Wahhab",
    "transliteration": "The Supreme Bestower",
    "meaning": "The One who is Generous in giving plenty without any return. He is everything that benefits whether Halal or Haram.",
  },
  {
    "arabic": "الرَّزَّاقُ",
    "latin": "Ar-Razzaq",
    "transliteration": "The Total Provider",
    "meaning": "The Sustainer, The Provider.",
  },
  {
    "arabic": "الْفَتَّاحُ",
    "latin": "Al-Fattah",
    "transliteration": "The Supreme Solver",
    "meaning": "The Opener, The Reliever, The Judge, The One who opens for His slaves the closed worldly and religious matters.",
  },
  {
    "arabic": "اَلْعَلِيْمُ",
    "latin": "Al-Alim",
    "transliteration": "The All-Knowing One",
    "meaning": "The Knowledgeable; The One nothing is absent from His knowledge",
  },
  {
    "arabic": "الْقَابِضُ",
    "latin": "Al-Qaabid",
    "transliteration": "The Restricting One",
    "meaning": "The Constrictor, The Withholder, The One who constricts the sustenance by His wisdom and expands and widens it with His Generosity and Mercy.",
  },
  {
    "arabic": "الْبَاسِطُ",
    "latin": "Al-Baasit",
    "transliteration": "The Extender",
    "meaning": "The Englarger, The One who constricts the sustenance by His wisdom and expands and widens it with His Generosity and Mercy.",
  },
  {
    "arabic": "الْخَافِضُ",
    "latin": "Al-Khaafid",
    "transliteration": "The Reducer",
    "meaning": "The Abaser, The One who lowers whoever He willed by His Destruction and raises whoever He willed by His Endowment.",
  },
  {
    "arabic": "الرَّافِعُ",
    "latin": "Ar-Rafi",
    "transliteration": "The Elevating One",
    "meaning": "The Exalter, The Elevator, The One who lowers whoever He willed by His Destruction and raises whoever He willed by His Endowment.",
  },
  {
    "arabic": "الْمُعِزُّ",
    "latin": "Al-Mu’izz",
    "transliteration": "The Honourer-Bestower",
    "meaning": "He gives esteem to whoever He willed, hence there is no one to degrade Him; And He degrades whoever He willed, hence there is no one to give Him esteem.",
  },
  {
    "arabic": "المُذِلُّ",
    "latin": "Al-Muzil",
    "transliteration": "The Abaser",
    "meaning": "The Dishonourer, The Humiliator, He gives esteem to whoever He willed, hence there is no one to degrade Him; And He degrades whoever He willed, hence there is no one to give Him esteem.",
  },
  {
    "arabic": "السَّمِيعُ",
    "latin": "As-Sami’",
    "transliteration": "The All-Hearer",
    "meaning": "The Hearer, The One who Hears all things that are heard by His Eternal Hearing without an ear, instrument or organ.",
  },
  {
    "arabic": "الْبَصِيرُ",
    "latin": "Al-Baseer",
    "transliteration": "The All-Seeing",
    "meaning": "The All-Noticing, The One who Sees all things that are seen by His Eternal Seeing without a pupil or any other instrument.",
  },
  {
    "arabic": "الْحَكَمُ",
    "latin": "Al-Hakam",
    "transliteration": "The Impartial Judge",
    "meaning": "The Judge, He is the Ruler and His judgment is His Word.",
  },
  {
    "arabic": "الْعَدْلُ",
    "latin": "Al-Adl",
    "transliteration": "The Embodiment of Justice",
    "meaning": "The Just, The One who is entitled to do what He does.",
  },
  {
    "arabic": "اللَّطِيفُ",
    "latin": "Al-Lateef",
    "transliteration": "The Knower of Subtleties",
    "meaning": "The Subtle One, The Gracious, The One who is kind to His slaves and endows upon them.",
  },
  {
    "arabic": "الْخَبِيرُ",
    "latin": "Al-Khabeer",
    "transliteration": "The All-Aware One",
    "meaning": "The One who knows the truth of things.",
  },
  {
    "arabic": "الْحَلِيمُ",
    "latin": "Al-Haleem",
    "transliteration": "The Clement One",
    "meaning": "The Forebearing, The One who delays the punishment for those who deserve it and then He might forgive them.",
  },
  {
    "arabic": "الْعَظِيمُ",
    "latin": "Al-Azeem",
    "transliteration": "The Magnificent One",
    "meaning": "The Great One, The Mighty, The One deserving the attributes of Exaltment, Glory, Extolement, and Purity from all imperfection.",
  },
  {
    "arabic": "الْغَفُورُ",
    "latin": "Al-Ghafoor",
    "transliteration": "The Great Forgiver",
    "meaning": "The All-Forgiving, The Forgiving, The One who forgives a lot.",
  },
  {
    "arabic": "الشَّكُورُ",
    "latin": "Ash-Shakoor",
    "transliteration": "The Acknowledging One",
    "meaning": "The Grateful, The Appreciative, The One who gives a lot of reward for a little obedience.",
  },
  {
    "arabic": "الْعَلِيُّ",
    "latin": "Al-Aliyy",
    "transliteration": "The Sublime One",
    "meaning": "The Most High, The One who is clear from the attributes of the creatures.",
  },
  {
    "arabic": "الْكَبِيرُ",
    "latin": "Al-Kabeer",
    "transliteration": "The Great One",
    "meaning": "The Most Great, The Great, The One who is greater than everything in status.",
  },
  {
    "arabic": "الْحَفِيظُ",
    "latin": "Al-Hafiz",
    "transliteration": "The Guarding One",
    "meaning": "The Preserver, The Protector, The One who protects whatever and whoever He willed to protect.",
  },
  {
    "arabic": "المُقيِت",
    "latin": "Al-Muqeet",
    "transliteration": "The Sustaining One",
    "meaning": "The Maintainer, The Guardian, The Feeder, The One who has the Power.",
  },
  {
    "arabic": "الْحسِيبُ",
    "latin": "Al-Haseeb",
    "transliteration": "The Reckoning One",
    "meaning": "The Reckoner, The One who gives the satisfaction.",
  },
  {
    "arabic": "الْجَلِيلُ",
    "latin": "Al-Jaleel",
    "transliteration": "The Majestic One",
    "meaning": "The Sublime One, The Beneficent, The One who is attributed with greatness of Power and Glory of status.",
  },
  {
    "arabic": "الْكَرِيمُ",
    "latin": "Al-Kareem",
    "transliteration": "The Bountiful One",
    "meaning": "The Generous One, The Gracious, The One who is attributed with greatness of Power and Glory of status.",
  },
  {
    "arabic": "الرَّقِيبُ",
    "latin": "Ar-Raqeeb",
    "transliteration": "The Watchful One",
    "meaning": "The Watcher, The One that nothing is absent from Him. Hence it’s meaning is related to the attribute of Knowledge.",
  },
  {
    "arabic": "الْمُجِيبُ",
    "latin": "Al-Mujeeb",
    "transliteration": "The Responding One",
    "meaning": "The Responsive, The Hearkener, The One who answers the one in need if he asks Him and rescues the yearner if he calls upon Him.",
  },
  {
    "arabic": "الْوَاسِعُ",
    "latin": "Al-Waasi’",
    "transliteration": "The All-Pervading One",
    "meaning": "The Vast, The All-Embracing, The Knowledgeable.",
  },
  {
    "arabic": "الْحَكِيمُ",
    "latin": "Al-Hakeem",
    "transliteration": "The Wise One",
    "meaning": "The Wise, The Judge of Judges, The One who is correct in His doings.",
  },
  {
    "arabic": "الْوَدُودُ",
    "latin": "Al-Wadud",
    "transliteration": "The Loving One",
    "meaning": "The One who loves His believing slaves and His believing slaves love Him. His love to His slaves is His Will to be merciful to them and praise them",
  },
  {
    "arabic": "الْمَجِيدُ",
    "latin": "Al-Majeed",
    "transliteration": "The Glorious One",
    "meaning": "The Most Glorious One, The One who is with perfect Power, High Status, Compassion, Generosity and Kindness.",
  },
  {
    "arabic": "الْبَاعِثُ",
    "latin": "Al-Ba’ith",
    "transliteration": "The Infuser of New Life",
    "meaning": "The Resurrector, The Raiser (from death), The One who resurrects His slaves after death for reward and/or punishment.",
  },
  {
    "arabic": "الشَّهِيدُ",
    "latin": "Ash-Shaheed",
    "transliteration": "The All Observing Witness",
    "meaning": "The Witness, The One who nothing is absent from Him.",
  },
  {
    "arabic": "الْحَقُّ",
    "latin": "Al-Haqq",
    "transliteration": "The Embodiment of Truth",
    "meaning": "The Truth, The True, The One who truly exists.",
  },
  {
    "arabic": "الْوَكِيلُ",
    "latin": "Al-Wakeel",
    "transliteration": "The Universal Trustee",
    "meaning": "The Trustee, The One who gives the satisfaction and is relied upon.",
  },
  {
    "arabic": "الْقَوِيُّ",
    "latin": "Al-Qawwiyy",
    "transliteration": "The Strong One",
    "meaning": "The Most Strong, The Strong, The One with the complete Power",
  },
  {
    "arabic": "الْمَتِينُ",
    "latin": "Al-Mateen",
    "transliteration": "The Firm One",
    "meaning": "The One with extreme Power which is un-interrupted and He does not get tired.",
  },
  {
    "arabic": "الْوَلِيُّ",
    "latin": "Al-Waliyy",
    "transliteration": "The Protecting Associate",
    "meaning": "The Protecting Friend, The Supporter.",
  },
  {
    "arabic": "الْحَمِيدُ",
    "latin": "Al-Hameed",
    "transliteration": "The Sole-Laudable One",
    "meaning": "The Praiseworthy, The praised One who deserves to be praised.",
  },
  {
    "arabic": "الْمُحْصِي",
    "latin": "Al-Muhsee",
    "transliteration": "The All-Enumerating One",
    "meaning": "The Counter, The Reckoner, The One who the count of things are known to him.",
  },
  {
    "arabic": "الْمُبْدِئُ",
    "latin": "Al-Mubdi",
    "transliteration": "The Originator",
    "meaning": "The One who started the human being. That is, He created him.",
  },
  {
    "arabic": "الْمُعِيدُ",
    "latin": "Al-Mueed",
    "transliteration": "The Restorer",
    "meaning": "The Reproducer, The One who brings back the creatures after death",
  },
  {
    "arabic": "الْمُحْيِي",
    "latin": "Al-Muhyi",
    "transliteration": "The Maintainer of life",
    "meaning": "The Restorer, The Giver of Life, The One who took out a living human from semen that does not have a soul. He gives life by giving the souls back to the worn out bodies on the resurrection day and He makes the hearts alive by the light of knowledge.",
  },
  {
    "arabic": "اَلْمُمِيتُ",
    "latin": "Al-Mumeet",
    "transliteration": "The Inflictor of Death",
    "meaning": "The Creator of Death, The Destroyer, The One who renders the living dead.",
  },
  {
    "arabic": "الْحَيُّ",
    "latin": "Al-Hayy",
    "transliteration": "The Eternally Living One",
    "meaning": "The Alive, The One attributed with a life that is unlike our life and is not that of a combination of soul, flesh or blood.",
  },
  {
    "arabic": "الْقَيُّومُ",
    "latin": "Al-Qayyoom",
    "transliteration": "The Self-Subsisting One",
    "meaning": "The One who remains and does not end.",
  },
  {
    "arabic": "الْوَاجِدُ",
    "latin": "Al-Waajid",
    "transliteration": "The Pointing One",
    "meaning": "The Perceiver, The Finder, The Rich who is never poor. Al-Wajd is Richness.",
  },
  {
    "arabic": "الْمَاجِدُ",
    "latin": "Al-Maajid",
    "transliteration": "The All-Noble One",
    "meaning": "The Glorious, He who is Most Glorious.",
  },
  {
    "arabic": "الْواحِدُ",
    "latin": "Al-Waahid",
    "transliteration": "The Only One",
    "meaning": "The Unique, The One, The One without a partner",
  },
  {
    "arabic": "اَلاَحَدُ",
    "latin": "Al-Ahad",
    "transliteration": "The Sole One",
    "meaning": "The One",
  },
  {
    "arabic": "الصَّمَدُ",
    "latin": "As-Samad",
    "transliteration": "The Supreme Provider",
    "meaning": "The Eternal, The Independent, The Master who is relied upon in matters and reverted to in ones needs.",
  },
  {
    "arabic": "الْقَادِرُ",
    "latin": "Al-Qaadir",
    "transliteration": "The Omnipotent One",
    "meaning": "The Able, The Capable, The One attributed with Power",
  },
  {
    "arabic": "الْمُقْتَدِرُ",
    "latin": "Al-Muqtadir",
    "transliteration": "The All Authoritative One",
    "meaning": "The Powerful, The Dominant, The One with the perfect Power that nothing is withheld from Him.",
  },
  {
    "arabic": "الْمُقَدِّمُ",
    "latin": "Al-Muqaddim",
    "transliteration": "The Expediting One",
    "meaning": "The Expediter, The Promoter, The One who puts things in their right places. He makes ahead what He wills and delays what He wills.",
  },
  {
    "arabic": "الْمُؤَخِّرُ",
    "latin": "Al-Mu’akhkhir",
    "transliteration": "The Procrastinator",
    "meaning": "The Delayer, the Retarder, The One who puts things in their right places. He makes ahead what He wills and delays what He wills.",
  },
  {
    "arabic": "الأوَّلُ",
    "latin": "Al-Awwal",
    "transliteration": "The Very First",
    "meaning": "The First, The One whose Existence is without a beginning.",
  },
  {
    "arabic": "الآخِرُ",
    "latin": "Al-Akhir",
    "transliteration": "The Infinite Last One",
    "meaning": "The Last, The One whose Existence is without an end.",
  },
  {
    "arabic": "الظَّاهِرُ",
    "latin": "Az-Zaahir",
    "transliteration": "The Perceptible",
    "meaning": "The Manifest, The One that nothing is above Him and nothing is underneath Him, hence He exists without a place. He, The Exalted, His Existence is obvious by proofs and He is clear from the delusions of attributes of bodies.",
  },
  {
    "arabic": "الْبَاطِنُ",
    "latin": "Al-Baatin",
    "transliteration": "The Imperceptible",
    "meaning": "The Hidden, The One that nothing is above Him and nothing is underneath Him, hence He exists without a place. He, The Exalted, His Existence is obvious by proofs and He is clear from the delusions of attributes of bodies.",
  },
  {
    "arabic": "الْوَالِي",
    "latin": "Al-Waali",
    "transliteration": "The Holder of Supreme Authority",
    "meaning": "The Governor, The One who owns things and manages them.",
  },
  {
    "arabic": "الْمُتَعَالِي",
    "latin": "Al-Muta’ali",
    "transliteration": "The Extremely Exalted One",
    "meaning": "The Most Exalted, The High Exalted, The One who is clear from the attributes of the creation.",
  },
  {
    "arabic": "الْبَرُّ",
    "latin": "Al-Barr",
    "transliteration": "The Fountain-Head of Truth",
    "meaning": "The Source of All Goodness, The Righteous, The One who is kind to His creatures, who covered them with His sustenance and specified whoever He willed among them by His support, protection, and special mercy.",
  },
  {
    "arabic": "التَّوَابُ",
    "latin": "At-Tawwaab",
    "transliteration": "The Ever-Acceptor of Repentance",
    "meaning": "The Ever-Acceptor of Repentance",
  },
  {
    "arabic": "الْمُنْتَقِمُ",
    "latin": "Al-Muntaqim",
    "transliteration": "The Retaliator",
    "meaning": "The Avenger, The One who victoriously prevails over His enemies and punishes them for their sins. It may mean the One who destroys them.",
  },
  {
    "arabic": "العَفُوُّ",
    "latin": "Al-Afuww",
    "transliteration": "The Supreme Pardoner",
    "meaning": "The Forgiver, The One with wide forgiveness.",
  },
  {
    "arabic": "الرَّؤُوفُ",
    "latin": "Ar-Ra’oof",
    "transliteration": "The Benign One",
    "meaning": "The Compassionate, The One with extreme Mercy. The Mercy of Allah is His will to endow upon whoever He willed among His creatures.",
  },
  {
    "arabic": "مَالِكُ الْمُلْكِ",
    "latin": "Maalik-ul-Mulk",
    "transliteration": "The Eternal Possessor of Sovereignty",
    "meaning": "The One who controls the Dominion and gives dominion to whoever He willed.",
  },
  {
    "arabic": "ذُوالْجَلاَلِ وَالإكْرَامِ",
    "latin": "Zul-Jalaali-wal-Ikram",
    "transliteration": "The Possessor of Majesty and Honour",
    "meaning": "The Lord of Majesty and Bounty, The One who deserves to be Exalted and not denied.",
  },
  {
    "arabic": "الْمُقْسِطُ",
    "latin": "Al-Muqsit",
    "transliteration": "The Just One",
    "meaning": "The Equitable, The One who is Just in His judgment.",
  },
  {
    "arabic": "الْجَامِعُ",
    "latin": "Al-Jaami’",
    "transliteration": "The Assembler of Scattered Creations",
    "meaning": "The Gatherer, The One who gathers the creatures on a day that there is no doubt about, that is the Day of Judgment.",
  },
  {
    "arabic": "الْغَنِيُّ",
    "latin": "Al-Ghaniyy",
    "transliteration": "The Self-Sufficient One",
    "meaning": "The One who does not need the creation.",
  },
  {
    "arabic": "الْمُغْنِي",
    "latin": "Al-Mughni",
    "transliteration": "The Bestower of Sufficiency",
    "meaning": "The Enricher, The One who satisfies the necessities of the creatures.",
  },
  {
    "arabic": "اَلْمَانِعُ",
    "latin": "Al-Maani’",
    "transliteration": "The Preventer",
    "meaning": "The Withholder.",
  },
  {
    "arabic": "الضَّارَّ",
    "latin": "Ad-Daarr",
    "transliteration": "The Distressor",
    "meaning": "The One who makes harm reach to whoever He willed and benefit to whoever He willed.",
  },
  {
    "arabic": "النَّافِعُ",
    "latin": "An-Naafi’",
    "transliteration": "The Bestower of Benefits",
    "meaning": "The Propitious, The One who makes harm reach to whoever He willed and benefit to whoever He willed.",
  },
  {
    "arabic": "النُّورُ",
    "latin": "An-Noor",
    "transliteration": "The Prime Light",
    "meaning": "The Light, The One who guides.",
  },
  {
    "arabic": "الْهَادِي",
    "latin": "Al-Haadi",
    "transliteration": "The Provider of Guidance",
    "meaning": "The Guide, The One whom with His Guidance His believers were guided, and with His Guidance the living beings have been guided to what is beneficial for them and protected from what is harmful to them.",
  },
  {
    "arabic": "الْبَدِيعُ",
    "latin": "Al-Badi’",
    "transliteration": "The Unique One",
    "meaning": "The Incomparable, The One who created the creation and formed it without any preceding example.",
  },
  {
    "arabic": "اَلْبَاقِي",
    "latin": "Al-Baaqi",
    "transliteration": "The Ever Surviving One",
    "meaning": "The Everlasting, The One that the state of non-existence is impossible for Him.",
  },
  {
    "arabic": "الْوَارِثُ",
    "latin": "Al-Waaris",
    "transliteration": "The Eternal Inheritor",
    "meaning": "The Heir, The One whose Existence remains.",
  },
  {
    "arabic": "الرَّشِيدُ",
    "latin": "Ar-Rasheed",
    "transliteration": "The Guide to Path of Rectitude",
    "meaning": "The Guide to the Right Path, The One who guides.",
  },
  {
    "arabic": "الصَّبُورُ",
    "latin": "As-Saboor",
    "transliteration": "The Extensively Enduring One",
    "meaning": "The Extensively Enduring One",
  },
]
